### ISSUE TITLE
dataloader.py errors when executing main.py

### ISSUE THREAD

**Issue by desk-champ** [PanosAntoniadis/emotion-gcn#8]
I recently tried to run the main.py script in VScode. However, after filling out the correct parser arguments I am receiving these errors. 
If you could please provide some context as to what I need to do to resolve these errors, it would be greatly appreciated. 

If more context is needed on the situation, I am happy to provide it.

--------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 292, in <module>
    main()
  File "main.py", line 226, in main
    train_dataloader, model, criterion_cat, optimizer)
  File "C:\Users\upf962\Downloads\CREST_MECIS_19401\Folders_from_workstation\emotion-gcn\training.py", line 10, in train_model_single
    for index, batch in enumerate(dataloader, 1):
  File "C:\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\Python37\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\upf962\Downloads\CREST_MECIS_19401\Folders_from_workstation\emotion-gcn\dataloading.py", line 74, in __getitem__
    image = self.transform(image)
  File "C:\Python37\lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
  File "C:\Python37\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python37\lib\site-packages\torchvision\transforms\transforms.py", line 346, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "C:\Python37\lib\site-packages\torchvision\transforms\functional.py", line 462, in resize
    _, image_height, image_width = get_dimensions(img)
  File "C:\Python37\lib\site-packages\torchvision\transforms\functional.py", line 75, in get_dimensions
    return F_pil.get_dimensions(img)
  File "C:\Python37\lib\site-packages\torchvision\transforms\functional_pil.py", line 33, in get_dimensions
    raise TypeError(f"Unexpected type {type(img)}")
TypeError: Unexpected type <class 'numpy.ndarray'>

**Comment by PanosAntoniadis** [comment]
Hello @desk-champ! Can you please provide the arguments that you used when you got this error?

**Comment by desk-champ** [comment]
Hi @PanosAntoniadis , I have provided the entered arguments which resulted in the error above. Please let me know if you need anymore context, I appreciate your response! 

![image](https://user-images.githubusercontent.com/96967556/206589743-598d435b-2b3d-4b31-9766-3f12ac684789.png)
![image](https://user-images.githubusercontent.com/96967556/206589779-0af56506-48f0-4adc-9aa5-6d26d62ebc23.png)

**Comment by desk-champ** [comment]
I was able to solve this error by converting the image from a numpy array into a PIL image. This was done by adding the following line of code to the dataloading.py script under the __getitem__(self, idx) function: 
```
# Convert the NumPy array to a PIL Image
image = Image.fromarray(image_R)
```
```
def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
        # Get selected sample
        sample = self.data[idx]
        # Read image
        img_name = os.path.join(self.root_dir, sample.image_path)
        image_R = cv2.imread(img_name)[..., ::-1]

        # Inserted line of code below:
        # Convert the NumPy array to a PIL Image
        image = Image.fromarray(image_R)
```
